### ISSUE TITLE
EtherCon connections

### ISSUE THREAD

**Issue by rjmunro** [Ramzeus/ah_ace_protocol#1]
In README.md, you say:

> If you find yourself in a situation where you want to connect the etherCON into a normal Ethernet switch it is usually possible to temporarily remove the outer connector “shield” by unscrewing it just like a XLR connector.

Much simpler than that is to just use a normal RJ45 ethernet cable. It will plug into the middle of etherCON socket and latch as it would into any other RJ45 socket, and you can completely ignore the shield. They are designed to be backwards compatible.

We have a ME-U and several ME-1s and they perform identically with etherCON cables and with normal network cables that we sometimes use if we don't have etherCON cables of the right length. No unscrewing or modding needed.

**Comment by PatrLind** [comment]
Hi @rjmunro, thanks for you comment!
What you say is of course true, but what I mean is that if you have a cable with etherCON connectors (quite common if you buy ready made armored cables), it is possible to use that cable as is by just unscrewing the connector shield from the cable. No need to use other cables than the ones you probably already have. But of course they are the same as a normal Ethernet cable of the same spec (at least electrically).
