### ISSUE TITLE
Convert the Audio

### ISSUE THREAD

**Issue by mediamarktluki** [Ramzeus/ah_ace_protocol#2]
Hi, in your Readme you say that you could convert the Audio into PCM Wav. Can you share your Method ?
Thank You

**Comment by PatrLind** [comment]
Hi @mediamarktluki, sorry I missed your comment.
In my research project I used byte order swap function to swap the bytes around so they become compatible with WAV files.
Here is how I call the function:
https://github.com/PatrLind/ah_ace_protocol/blob/b41df11dc9432c7d38d9e94268206577cb759e5b/src/research_test/main.cpp#L311

You can see the function implementation at:
https://github.com/PatrLind/ah_ace_protocol/blob/b41df11dc9432c7d38d9e94268206577cb759e5b/src/research_test/main.cpp#L105

Other than that I think the only thing needed is to either write a RIFF header to make applications recognize the format or using a RAW import function in a audio processing software (such as Audacity). You can see the RIFF WAV format described here: https://en.wikipedia.org/wiki/WAV

If you want to see how I wrote my WAV files you can take a look at this function:
https://github.com/PatrLind/ah_ace_protocol/blob/b41df11dc9432c7d38d9e94268206577cb759e5b/src/research_test/main.cpp#L53

I hope this helps.
